services:
  - type: worker
    name: nse-option-bot
    env: python
    plan: free
    runtime: "python3.11"
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python bt5.py
